export const MUGSOUND_DIRECTION_BATCH_ID = 'mugsound-direction-20260816-v2'
export const MUGSOUND_DIRECTION_LEGACY_BATCH_ID = 'mugsound-direction-20260816-v1'
export const MUGSOUND_DIRECTION_BATCH_IDS = [
  MUGSOUND_DIRECTION_BATCH_ID,
  MUGSOUND_DIRECTION_LEGACY_BATCH_ID,
] as const

export const MUGSOUND_PLAYLIST_TARGET_SECONDS = 180
export const MUGSOUND_MIN_QUALIFIED_DURATION_SECONDS = 150
export const MUGSOUND_MAX_QUALIFIED_DURATION_SECONDS = 270
